### PR TITLE
add stuaxo's cairo extension

### PR DESCRIPTION
**Pull request by fomightez**
Stuart got the extension working in the binderized cairo-jupyter. This merges in his fork to the main repo for cairo-jupyter.

### CODE REVIEW

**Comment by stuaxo** [comment]
Great :) I was going to squash my commits as the trial-and-error-ness of them is a little embarrassing, but no matter.

**Comment by fomightez** [comment]
Sorry. I can always re-do my pull if you really want to. I didn't change much after.

**Comment by stuaxo** [comment]
No probs, I'm too lazy.   I just noticed in interviews they tend to look at git repos I've contributed these days, but I'm sure these will get lost in the history.

**Comment by fomightez** [comment]
Sorry, I didn't even think of that. Silver lining in this case is that I obviously did the pull request. Plus, notebooks are notoriously problematic for version control. I'd be fine reverting if you reconsider later.

**Comment by stuaxo** [comment]
Yep, great to have the PR done.

**Pull request merged**
